In [43]:
import pandas as pd
import numpy as np

In [44]:
df = pd.read_csv("giang.csv")

In [45]:
len(df[df["type"] == "SINGLE_FAMILY"])
df.head(5)

,Unnamed: 0,zpid,price,status,type,city,state,latitude,longitude,bathrooms,bedrooms,living_area,lot_area,lot_area_unit,days_on_zillow
0,0,2.073568e+09,4980000.0,House for sale,SINGLE_FAMILY,West Hollywood,CA,34.100803,-118.380570,5.0,4.0,4126.0,4922.0000,sqft,7.908150e+08
1,1,1.987515e+07,1215000.0,House for sale,SINGLE_FAMILY,Woodland Hills,CA,34.180298,-118.642500,2.0,3.0,1825.0,7840.8000,sqft,1.020029e+09
2,2,2.053261e+07,2629000.0,House for sale,SINGLE_FAMILY,Beverly Hills,CA,34.112854,-118.433876,4.0,4.0,3019.0,0.9959,acres,4.203270e+08
3,3,NaN,NaN,For Rent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.008299e+09
4,4,2.093480e+07,400000.0,Multi-family home for sale,MULTI_FAMILY,Los Angeles,CA,33.978700,-118.295680,2.0,3.0,944.0,4268.8800,sqft,9.995380e+08

In [46]:
print(
    df.nlargest(
        30,
        "lot_area"
    )[[
        "living_area",
        "lot_area",
        "lot_area_unit",
    ]]
)

      living_area   lot_area lot_area_unit
4349       5966.0  47000.000         acres
499        1400.0  10886.000          sqft
1624       1900.0  10880.000          sqft
576        5354.0  10872.576          sqft
4396       3080.0  10846.440          sqft
4117       2125.0  10829.016          sqft
3014       3664.0  10825.000          sqft
3047        908.0  10790.000          sqft
4203       4551.0  10785.456          sqft
3169       2200.0  10779.000          sqft
3113        950.0  10776.000          sqft
3132        950.0  10776.000          sqft
1388       3956.0  10768.032          sqft
5686       2548.0  10750.608          sqft
4496       1482.0  10724.472          sqft
4501       1899.0  10723.000          sqft
2744       1680.0  10720.116          sqft
1558       1415.0  10715.000          sqft
845         985.0  10702.692          sqft
287        3258.0  10698.336          sqft
3280       1088.0  10686.000          sqft
331        2850.0  10667.844          sqft
4331       4538.0  10641.708          sqft
3362       1753.0  10599.000          sqft
2696       1900.0  10598.148          sqft
1762       2138.0  10588.000          sqft
3227       1875.0  10583.000          sqft
44         4860.0  10582.000          sqft
290        2382.0  10570.000          sqft
378        2038.0  10545.000          sqft

In [47]:
#CHỈ LẤY SINGLE_FAMILY
df = df[df["type"] == "SINGLE_FAMILY"]

In [48]:
df.head(5)

,Unnamed: 0,zpid,price,status,type,city,state,latitude,longitude,bathrooms,bedrooms,living_area,lot_area,lot_area_unit,days_on_zillow
0,0,2.073568e+09,4980000.0,House for sale,SINGLE_FAMILY,West Hollywood,CA,34.100803,-118.380570,5.0,4.0,4126.0,4922.0000,sqft,7.908150e+08
1,1,1.987515e+07,1215000.0,House for sale,SINGLE_FAMILY,Woodland Hills,CA,34.180298,-118.642500,2.0,3.0,1825.0,7840.8000,sqft,1.020029e+09
2,2,2.053261e+07,2629000.0,House for sale,SINGLE_FAMILY,Beverly Hills,CA,34.112854,-118.433876,4.0,4.0,3019.0,0.9959,acres,4.203270e+08
5,5,2.131354e+07,849000.0,House for sale,SINGLE_FAMILY,San Pedro,CA,33.713604,-118.291880,2.0,2.0,1154.0,5002.0000,sqft,6.436090e+08
6,6,2.064446e+07,949000.0,House for sale,SINGLE_FAMILY,Los Angeles,CA,34.067300,-118.172520,2.0,3.0,2158.0,9857.6280,sqft,4.977220e+08

bathrooms, bedrooms, living_area
Số lượng thiếu quá ít: Xóa luôn

In [49]:
print(len(df[df["lot_area"] == 0]))
print(len(df[df["bedrooms"] == 0]))
print(len(df[df["bathrooms"] == 0]))
print(len(df[df["living_area"] == 0]))
print(len(df[df["price"] == 0]))

7
13
4
47
36

In [50]:
df.loc[df["lot_area"] == 0, "lot_area"] = np.nan
df.loc[df["bedrooms"] == 0, "bedrooms"] = np.nan
df.loc[df["bathrooms"] == 0, "bathrooms"] = np.nan
df.loc[df["living_area"] == 0, "living_area"] = np.nan
df.loc[df["price"] == 0, "price"] = np.nan

In [51]:
df = df.dropna(
    subset=[
        "bathrooms",
        "bedrooms",
        "living_area",
        "lot_area",
        "price"
    ]
)

In [52]:
print(df.isnull().sum())

Unnamed: 0        0
zpid              0
price             0
status            0
type              0
city              0
state             0
latitude          0
longitude         0
bathrooms         0
bedrooms          0
living_area       0
lot_area          0
lot_area_unit     0
days_on_zillow    0
dtype: int64

In [53]:
print(
    df.nlargest(
        30,
        "lot_area"
    )[[
        "city",
        "price",
        "lot_area",

        "lot_area_unit",
    ]]
)

                  city       price   lot_area lot_area_unit
4349            Malibu   7995000.0  47000.000         acres
499             Reseda    999999.0  10886.000          sqft
1624         San Diego    799999.0  10880.000          sqft
576      San Francisco   3295000.0  10872.576          sqft
4396            Malibu   3275000.0  10846.440          sqft
4117             Davis    949000.0  10829.016          sqft
3014     Big Bear Lake   1199900.0  10825.000          sqft
3047     Big Bear Lake    420000.0  10790.000          sqft
4203            Malibu  34800000.0  10785.456          sqft
3169     Big Bear Lake    875000.0  10779.000          sqft
1388       Bakersfield    715000.0  10768.032          sqft
5686       Guerneville   1575000.0  10750.608          sqft
2744  South Lake Tahoe    699000.0  10720.116          sqft
1558        San Ysidro    595000.0  10715.000          sqft
287      Beverly Hills   3498000.0  10698.336          sqft
3280     Big Bear Lake    449900.0  10686.000          sqft
331        Los Angeles   2575000.0  10667.844          sqft
4331            Malibu  12500000.0  10641.708          sqft
3362     Big Bear Lake    875000.0  10599.000          sqft
2696  South Lake Tahoe    859000.0  10598.148          sqft
1762         San Diego   3150000.0  10588.000          sqft
3227     Big Bear Lake    859900.0  10583.000          sqft
44        Sherman Oaks   3595000.0  10582.000          sqft
290     Woodland Hills   1695000.0  10570.000          sqft
378          San Pedro   1575000.0  10545.000          sqft
3319     Big Bear Lake    784000.0  10539.000          sqft
1851         San Diego   1380000.0  10500.000          sqft
3190     Big Bear Lake    830000.0  10500.000          sqft
142        Los Angeles   5195000.0  10493.604          sqft
5740         Oceanside    999999.0  10491.000          sqft

In [54]:
mask = (
    (df["lot_area_unit"] == "acres") &
    (df["lot_area"] > 500)
)
print(df[mask])

      Unnamed: 0         zpid      price          status           type  \
1052        1052  249713107.0   567999.0  House for sale  SINGLE_FAMILY
1705        1705   16868695.0   899000.0     Coming soon  SINGLE_FAMILY
3984        3984  249320381.0  1500000.0  House for sale  SINGLE_FAMILY
4349        4349   20557106.0  7995000.0  House for sale  SINGLE_FAMILY
5731        5731   16592243.0   949900.0  House for sale  SINGLE_FAMILY

             city state   latitude   longitude  bathrooms  bedrooms  \
1052  Bakersfield    CA  35.321346 -119.135770        4.0       3.0
1705    San Diego    CA  32.815613 -117.044900        2.0       4.0
3984      Alturas    CA  41.447056 -120.651210        1.0       3.0
4349       Malibu    CA  34.029770 -118.833565        4.0       4.0
5731    Oceanside    CA  33.242683 -117.327870        2.0       4.0

      living_area  lot_area lot_area_unit  days_on_zillow
1052       2205.0    4791.0         acres    6.623390e+08
1705       1789.0    6100.0         acres    1.322100e+08
3984       1088.0    2302.0         acres    7.263784e+10
4349       5966.0   47000.0         acres    1.311678e+10
5731       2067.0    6000.0         acres    8.099968e+09

In [55]:
#Kiểm tra cái bị đánh nhầm lot_area_unit
df[df["lot_area_unit"]=="acres"] \
    .sort_values("lot_area", ascending=False) \
    [["city","price","living_area","lot_area"]] \
    .head(30)

                  city       price  living_area    lot_area
4349            Malibu   7995000.0       5966.0  47000.0000
1705         San Diego    899000.0       1789.0   6100.0000
5731         Oceanside    949900.0       2067.0   6000.0000
1052       Bakersfield    567999.0       2205.0   4791.0000
3984           Alturas   1500000.0       1088.0   2302.0000
3952           Alturas   2175000.0       5200.0    260.0000
5684       Guerneville   1495000.0        768.0    120.0000
5111   Rancho Santa Fe  84950000.0      15000.0     77.0000
5054     Santa Barbara   4750000.0       5316.0     45.6000
5045     Santa Barbara   4750000.0       5316.0     45.6000
4250            Malibu   6950000.0       4739.0     38.8300
3966           Alturas    745000.0       2700.0     36.0000
4431            Malibu   5100000.0       1400.0     30.0000
5667       Guerneville   1399000.0       1176.0     22.4000
4289            Malibu   5999000.0       4246.0     21.6694
3958           Alturas    285000.0       1440.0     20.7300
5280          Paradise    959000.0       3001.0     20.0100
4819           Truckee   2700000.0       5900.0     20.0000
4216            Malibu   3495000.0       3850.0     19.8730
3962           Alturas    564000.0       1436.0     19.6900
2637  South Lake Tahoe  18500000.0      16500.0     15.3400
5216          Paradise    655000.0       2170.0     14.8900
2634  South Lake Tahoe   4200000.0       2858.0     12.9000
4448            Malibu   7750000.0       5350.0     11.0229
4241            Malibu   3869000.0       3856.0     11.0082
4142             Davis   1699000.0       2311.0     10.9000
5030         Montecito  65000000.0      13629.0     10.5000
3947           Alturas    420000.0       2000.0     10.0600
5038     Santa Barbara   6499000.0       3726.0     10.0100
4391            Malibu   3695000.0       2570.0      9.8584

In [56]:
# mấy cái trên 1000 sẽ tính là sqft
mask = (
    (df["lot_area_unit"] == "acres") &
    (df["lot_area"] > 1000)
)

# sửa các dòng nghi ngờ bị gắn nhầm đơn vị
df.loc[mask, "lot_area_unit"] = "sqft"

# tạo cột chuẩn sqft
df["lot_sqft"] = np.where(
    df["lot_area_unit"] == "acres",
    df["lot_area"] * 43560,
    df["lot_area"]
)

In [57]:
print(
    df.nlargest(
        30,
        "lot_area"
    )[[
        "city",
        "price",
        "lot_area",

        "lot_area_unit",
    ]]
)

                  city       price   lot_area lot_area_unit
4349            Malibu   7995000.0  47000.000          sqft
499             Reseda    999999.0  10886.000          sqft
1624         San Diego    799999.0  10880.000          sqft
576      San Francisco   3295000.0  10872.576          sqft
4396            Malibu   3275000.0  10846.440          sqft
4117             Davis    949000.0  10829.016          sqft
3014     Big Bear Lake   1199900.0  10825.000          sqft
3047     Big Bear Lake    420000.0  10790.000          sqft
4203            Malibu  34800000.0  10785.456          sqft
3169     Big Bear Lake    875000.0  10779.000          sqft
1388       Bakersfield    715000.0  10768.032          sqft
5686       Guerneville   1575000.0  10750.608          sqft
2744  South Lake Tahoe    699000.0  10720.116          sqft
1558        San Ysidro    595000.0  10715.000          sqft
287      Beverly Hills   3498000.0  10698.336          sqft
3280     Big Bear Lake    449900.0  10686.000          sqft
331        Los Angeles   2575000.0  10667.844          sqft
4331            Malibu  12500000.0  10641.708          sqft
3362     Big Bear Lake    875000.0  10599.000          sqft
2696  South Lake Tahoe    859000.0  10598.148          sqft
1762         San Diego   3150000.0  10588.000          sqft
3227     Big Bear Lake    859900.0  10583.000          sqft
44        Sherman Oaks   3595000.0  10582.000          sqft
290     Woodland Hills   1695000.0  10570.000          sqft
378          San Pedro   1575000.0  10545.000          sqft
3319     Big Bear Lake    784000.0  10539.000          sqft
1851         San Diego   1380000.0  10500.000          sqft
3190     Big Bear Lake    830000.0  10500.000          sqft
142        Los Angeles   5195000.0  10493.604          sqft
5740         Oceanside    999999.0  10491.000          sqft

In [58]:
df.head(5)

,Unnamed: 0,zpid,price,status,type,city,state,latitude,longitude,bathrooms,bedrooms,living_area,lot_area,lot_area_unit,days_on_zillow,lot_sqft
0,0,2.073568e+09,4980000.0,House for sale,SINGLE_FAMILY,West Hollywood,CA,34.100803,-118.380570,5.0,4.0,4126.0,4922.0000,sqft,7.908150e+08,4922.000
1,1,1.987515e+07,1215000.0,House for sale,SINGLE_FAMILY,Woodland Hills,CA,34.180298,-118.642500,2.0,3.0,1825.0,7840.8000,sqft,1.020029e+09,7840.800
2,2,2.053261e+07,2629000.0,House for sale,SINGLE_FAMILY,Beverly Hills,CA,34.112854,-118.433876,4.0,4.0,3019.0,0.9959,acres,4.203270e+08,43381.404
5,5,2.131354e+07,849000.0,House for sale,SINGLE_FAMILY,San Pedro,CA,33.713604,-118.291880,2.0,2.0,1154.0,5002.0000,sqft,6.436090e+08,5002.000
6,6,2.064446e+07,949000.0,House for sale,SINGLE_FAMILY,Los Angeles,CA,34.067300,-118.172520,2.0,3.0,2158.0,9857.6280,sqft,4.977220e+08,9857.628

In [59]:
# Xóa các cột dưới
cols_to_drop = [
    "status",
    "type",
    "state",
    "Unnamed: 0",
    
]

df = df.drop(columns=cols_to_drop, errors="ignore")

In [60]:
df['days_on_zillow'] = df['days_on_zillow'] / 86400000

In [61]:
df.head(5)

,zpid,price,city,latitude,longitude,bathrooms,bedrooms,living_area,lot_area,lot_area_unit,days_on_zillow,lot_sqft
0,2.073568e+09,4980000.0,West Hollywood,34.100803,-118.380570,5.0,4.0,4126.0,4922.0000,sqft,9.152951,4922.000
1,1.987515e+07,1215000.0,Woodland Hills,34.180298,-118.642500,2.0,3.0,1825.0,7840.8000,sqft,11.805891,7840.800
2,2.053261e+07,2629000.0,Beverly Hills,34.112854,-118.433876,4.0,4.0,3019.0,0.9959,acres,4.864896,43381.404
5,2.131354e+07,849000.0,San Pedro,33.713604,-118.291880,2.0,2.0,1154.0,5002.0000,sqft,7.449178,5002.000
6,2.064446e+07,949000.0,Los Angeles,34.067300,-118.172520,2.0,3.0,2158.0,9857.6280,sqft,5.760671,9857.628

In [62]:
df.to_csv("datasuperclean.csv")